name: Python CI/CD Workflow

on:
  # Run the workflow on pushes to the main branch and pull requests
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the GitHub repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # You can specify the Python version

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create a sample file
      run: |
        echo "hello raman boy!">raman.txt

    - name: upload the artifact
      uses: actions/upload-artifact@v4.6.2
      with:
       name: myartifact
       path: ./raman.txt
          
        
    # # Run unit tests
    # - name: Run tests
    #   run: |
    #     pytest

  lint:
    needs: test
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the GitHub repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: download the artifact
      uses: actions/download-artifact@v4.3.0
      with:
       name: myartifact

    # Install dependencies for linting
    - name: Install pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    # Run linter
    - name: Run Linter
      run: |
        pylint **/*.py
        cat raman.txt
