name: Python CI/CD Workflow

on:
  # Run the workflow on pushes to the main branch and pull requests
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job1:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Create a sample file
        run: |
          echo "${{ matrix.os }}"
      - name: step 2
        run: echo "step 2"

          
